# Generated by Django 2.0 on 2018-07-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_unique_key'),
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('zipcode', models.CharField(max_length=6)),
                ('tc', models.BooleanField(default=False)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Checkout')),
            ],
        ),
    ]
