# Generated by Django 2.0 on 2018-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_guestuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
