# Generated by Django 2.0 on 2018-07-12 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ambassador', '0002_ambassador_college_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Ambassador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
