# Generated by Django 2.0.6 on 2018-07-08 10:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_desc', models.TextField(max_length=500)),
                ('available', models.BooleanField(default=True)),
                ('communication_format', multiselectfield.db.fields.MultiSelectField(choices=[('wifi', 'WIFI'), ('sim', 'SIM'), ('ethernet', 'Ethernet'), ('bluetooth', 'Bluetooth'), ('lora', 'LORA')], max_length=32)),
                ('PortType', multiselectfield.db.fields.MultiSelectField(choices=[('U-ART', 'U-ART'), ('RS232', 'RS232'), ('RS485', 'RS485')], max_length=17)),
                ('PowerSource', multiselectfield.db.fields.MultiSelectField(choices=[('V1', '12V'), ('V2', '5V'), ('V3', '3.3V')], max_length=8)),
                ('storage', models.BooleanField(default=False)),
                ('antenna', models.BooleanField(default=False)),
                ('prod_price', models.FloatField(default=0, max_length=10)),
                ('sell_price', models.FloatField(default=0, max_length=10)),
            ],
        ),
    ]
