# Generated by Django 2.0.6 on 2018-07-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='actual_prices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
