# Generated by Django 2.0 on 2018-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_actual_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unique_key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
